### ISSUE TITLE
[BUG] @frontegg/redux-store/toolkit/index.js is ESM not CommonJS

### ISSUE THREAD

**Issue by sdemjanenko** [frontegg/frontegg-react#385]
I ran into an error in Jest when this file was loaded:
```
.../node_modules/@frontegg/redux-store/toolkit/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { bindActionCreators, combineReducers, configureStore, getDefaultMiddleware } from '@reduxjs/toolkit';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@frontegg/react-hooks/index.cjs.js:9:15)
```

I can probably get around this in my Jest config, but its likely that since this file is ESM, users may run into issues.

**Comment by frontegg-david** [comment]
Hi @sdemjanenko,
From version 3.3.0 @frontegg/redux-store built with CommonJS format.
